# Generated by Django 5.2.1 on 2025-06-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200, verbose_name='指令文本')),
                ('action', models.CharField(max_length=100, verbose_name='执行动作')),
                ('similarity_threshold', models.FloatField(default=0.7, verbose_name='相似度阈值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '语音指令',
                'verbose_name_plural': '语音指令',
            },
        ),
        migrations.CreateModel(
            name='SpeechRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='识别文本')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='匹配度')),
                ('executed', models.BooleanField(default=False, verbose_name='是否执行')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speech.voicecommand')),
            ],
            options={
                'verbose_name': '语音记录',
                'verbose_name_plural': '语音记录',
            },
        ),
    ]
